name: unit-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        # https://github.com/actions/go-versions/blob/main/versions-manifest.json
        go-version: 'stable'

    - name: Unit test
      run: make
